### ISSUE TITLE
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor

### ISSUE THREAD

**Issue by FatemehMashhadi** [guillaumegenthial/sequence_tagging#10]
I ran "python build_data.py" on my dataset and it was Ok but when i run "python main.py" to train  my model i get an error.
Here is the traceback:

C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\ops\gradients_impl.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2017-07-25 13:01:13.770555: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-07-25 13:01:13.780837: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-25 13:01:13.792198: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
Reloading the latest trained model...
INFO:tensorflow:Restoring parameters from /results/crf/model.weights/
Restoring parameters from /results/crf/model.weights/
2017-07-25 13:01:16.256308: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.256371: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.256429: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.256485: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.256525: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.256590: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.340877: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.284399: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.298523: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.312538: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.326592: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.270016: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.355930: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.370020: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.383945: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.397983: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.411831: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.425676: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.439582: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.453446: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.467343: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.481262: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.495121: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.509338: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.523517: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.537511: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.552983: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.566865: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.580697: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.594563: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.608358: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.622190: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.637740: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.651574: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.665625: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.679549: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.693420: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.707397: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

2017-07-25 13:01:16.722452: W c:\tf_jenkins\home\workspace\release-win\m\windows\py\35\tensorflow\core\framework\op_kernel.cc:1158] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

Traceback (most recent call last):
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
  File "C:\Users\New\Anaconda2\envs\python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

         [[Node: save/RestoreV2_38 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_38/tensor_names, save/RestoreV2_38/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 38, in <module>
    model.train(train, dev, vocab_tags)
  File "D:\Mashhadirajab\DeepNN-NER\sequence_tagging-master\sequence_tagging-master\model.py", line 340, in train
    saver.restore(sess, self.config.model_output)
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\training\saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

         [[Node: save/RestoreV2_38 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_38/tensor_names, save/RestoreV2_38/shape_and_slices)]]

Caused by op 'save/RestoreV2_38', defined at:
  File "main.py", line 38, in <module>
    model.train(train, dev, vocab_tags)
  File "D:\Mashhadirajab\DeepNN-NER\sequence_tagging-master\sequence_tagging-master\model.py", line 333, in train
    saver = tf.train.Saver()
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\training\saver.py", line 1139, in __init__
    self.build()
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\training\saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\training\saver.py", line 691, in build
    restore_sequentially, reshape)
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\training\saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\training\saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\New\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on /results/crf/model.weights/: Not found: FindFirstFile failed for: /results/crf/model.weights : The system cannot find the path specified.

         [[Node: save/RestoreV2_38 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_38/tensor_names, save/RestoreV2_38/shape_and_slices)]]

**Comment by FatemehMashhadi** [comment]
Do i set config.reload= false if i am going to train a new model and there is no any trained model for restore?

**Comment by guillaumegenthial** [comment]
yes! The default value to True from the latest pull request was misleading. I changed it!
