### ISSUE TITLE
KeyError: '$UNK$ on python main.py

### ISSUE THREAD

**Issue by matteoredaelli** [guillaumegenthial/sequence_tagging#16]
I got the following error: any suggestions?

Regards Matteo

Epoch 1 out of 15
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    main(config)
  File "main.py", line 36, in main
    model.train(train, dev, vocab_tags)
  File "/home/matteo/src/sequence_tagging/model.py", line 354, in train
    acc, f1 = self.run_epoch(sess, train, dev, tags, epoch)
  File "/home/matteo/src/sequence_tagging/model.py", line 280, in run_epoch
    nbatches = (len(train) + self.config.batch_size - 1) // self.config.batch_size
  File "/home/matteo/src/sequence_tagging/data_utils.py", line 87, in __len__
    for _ in self:
  File "/home/matteo/src/sequence_tagging/data_utils.py", line 76, in __iter__
    tag = self.processing_tag(tag)
  File "/home/matteo/src/sequence_tagging/data_utils.py", line 247, in f
    word = vocab_words[UNK]
KeyError: '$UNK$'

python3 build_data.py
Building vocab...
- done. 22 tokens
Building vocab...
- done. 400000 tokens
Writing vocab...
- done. 22 tokens
Writing vocab...
- done. 7 tokens
Writing vocab...
- done. 23 tokens

matteo@debian:~/src/sequence_tagging$ cat data/words.txt 
bicocca
$UNK$
eu
hangar
boycott
sui
british
giovanni
.
sulle
ess
german
italian
su
matteo
es
$NUM$
shop
it
to
luca

**Comment by guillaumegenthial** [comment]
Hi Matteo,
Sorry for the long delay. I hope you found the fix.
If not, I would say that this is most likely because your vocabulary of tags is incomplete and your training set has an unknown tag which shouldn't happen.
I committed a warning message and exception to handle that special case.
Best,
Guillaume
