### ISSUE TITLE
Unimplemented: TensorArray has size zero

### ISSUE THREAD

**Issue by gaoxiangyu369** [guillaumegenthial/sequence_tagging#52]
When I produced my data files as txt files followed the format [Word] [Label] and store them in the right location, I got an Error indicates that 

**Unimplemented: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.**

Does this problem happen to anyone?

**Comment by gaoxiangyu369** [comment]
11:28:01.244383: W tensorflow/core/framework/op_kernel.cc:1152] Unimplemented: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@rnn/TensorArray_1"], dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"](train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, rnn/TensorArrayUnstack/range, train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/gradient_flow)]]
2018-05-16 11:28:01.244397: W tensorflow/core/framework/op_kernel.cc:1152] Unimplemented: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@rnn/TensorArray_1"], dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"](train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, rnn/TensorArrayUnstack/range, train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/gradient_flow)]]
Traceback (most recent call last):
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/Users/shaun/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@rnn/TensorArray_1"], dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"](train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, rnn/TensorArrayUnstack/range, train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/gradient_flow)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 26, in <module>
    main()
  File "train.py", line 23, in main
    model.train(train, dev)
  File "/Users/shaun/Desktop/name_tag/sequence_tagging/model/base_model.py", line 121, in train
    score = self.run_epoch(train, dev, epoch)
  File "/Users/shaun/Desktop/name_tag/sequence_tagging/model/ner_model.py", line 290, in run_epoch
    [self.train_op, self.loss, self.merged], feed_dict=fd)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@rnn/TensorArray_1"], dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"](train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, rnn/TensorArrayUnstack/range, train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/gradient_flow)]]

Caused by op 'train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3', defined at:
  File "train.py", line 26, in <module>
    main()
  File "train.py", line 12, in main
    model.build()
  File "/Users/shaun/Desktop/name_tag/sequence_tagging/model/ner_model.py", line 227, in build
    self.config.clip)
  File "/Users/shaun/Desktop/name_tag/sequence_tagging/model/base_model.py", line 58, in add_train_op
    self.train_op = optimizer.minimize(loss)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 315, in minimize
    grad_loss=grad_loss)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 386, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 560, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 368, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 560, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_grad.py", line 186, in _TensorArrayScatterGrad
    grad = g.gather(indices)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 328, in gather
    element_shape=element_shape)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 2244, in _tensor_array_gather_v3
    element_shape=element_shape, name=name)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

...which was originally created as op 'rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3', defined at:
  File "train.py", line 26, in <module>
    main()
[elided 0 identical lines from previous traceback]
  File "train.py", line 12, in main
    model.build()
  File "/Users/shaun/Desktop/name_tag/sequence_tagging/model/ner_model.py", line 223, in build
    self.add_loss_op()
  File "/Users/shaun/Desktop/name_tag/sequence_tagging/model/ner_model.py", line 203, in add_loss_op
    self.logits, self.labels, self.sequence_lengths)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/crf/python/ops/crf.py", line 156, in crf_log_likelihood
    log_norm = crf_log_norm(inputs, sequence_lengths, transition_params)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/crf/python/ops/crf.py", line 123, in crf_log_norm
    dtype=dtypes.float32)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 553, in dynamic_rnn
    dtype=dtype)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 671, in _dynamic_rnn_loop
    for ta, input_ in zip(input_ta, flat_input))
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 671, in <genexpr>
    for ta, input_ in zip(input_ta, flat_input))
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 381, in unstack
    indices=math_ops.range(0, num_elements), value=value, name=name)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 409, in scatter
    name=name)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 2510, in _tensor_array_scatter_v3
    name=name)
  File "/Users/shaun/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)

UnimplementedError (see above for traceback): TensorArray has size zero, but element shape <unknown> is not fully defined. Currently only static shapes are supported when packing zero-size TensorArrays.
	 [[Node: train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@rnn/TensorArray_1"], dtype=DT_FLOAT, element_shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"](train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/TensorArrayGradV3, rnn/TensorArrayUnstack/range, train_step/gradients/rnn/TensorArrayUnstack/TensorArrayScatter/TensorArrayScatterV3_grad/TensorArrayGrad/gradient_flow)]]
